import React from "react";
import { Container, Col, Card } from "react-bootstrap";
import "./privacy_policy.css";
import Footer from "../HomeComponents/newfooter";

const Privacy = () => {
  return (
    <div>
      <div className="policy_page">
        <Container>
          <div className="privacy-title">
            <h2>Privacy Policy</h2>
          </div>
        </Container>
      </div>
      <div className="policy-section">
        <Container>
          <div className="centralized-content">
            <Col md={11} className="policy-content">
              <Card className="policy-card">
                <Card.Header className="policy-header">
                  Update at 2020-09-09
                </Card.Header>
                <Card.Body className="policy_card-body">
                  <p className="legal-cont">
                    {" "}
                    Yudimy (“we,” “our,” or “us”) is committed to protecting
                    your privacy. This Privacy Policy explains how your personal
                    information is collected, used, and disclosed by Yudimy.
                    This Privacy Policy applies to our website, and its
                    associated subdomains (collectively, our “Service”)
                    alongside our application, CLARITY. By accessing or using
                    our Service, you signify that you have read, understood, and
                    agree to our collection, storage, use, and disclosure of
                    your personal information as described in this Privacy
                    Policy and our Terms of Service.
                  </p>
                  <p><strong>Meanings</strong></p>
                  <p>
                    <strong>For this Privacy Policy:</strong>
                  </p>
                  <p className="legal-cont">
                    - You are referred to the person who accessed the Service,
                    or the company, or other legal entity on behalf of which
                    such individual is accessing or using the Service, as
                    applicable.
                    <br />
                    - Company (referred to as either "the Company", "We", "Us"
                    or "Our" in this Agreement) refers to Yudimy Services Ltd, 3
                    Samuel Street, Ogudu, Lagos.
                    <br />
                    -Website is referred to Yudimy.com or clarity.yudimy.com.
                    <br />
                    -Service is referred to the website/app i.e
                    clarity.yudimy.com.
                    <br />
                    -Service Provider means any natural or legal person who
                    processes the data on behalf of Yudimy. It refers to
                    third-party companies or individuals employed by Yudimy to
                    facilitate the Service, to provide the Service on behalf of
                    Yudimy, to perform services related to the Service or to
                    assist Yudimy in analysing how the Service is used.
                    <br />
                    -Third-party Social Media Service could be any website or
                    social network website in which a User can log in or create
                    an account to use the Service.
                    <br />
                    -Personal Data is any information that relates to an
                    identified or identifiable individual.
                    <br />
                    -Cookies are a small amount of data generated by a website
                    and saved by your web browser. Its purpose is to remember
                    information about you, similar to a preference file created
                    by a software application.
                    <br />
                    -Device could be any device with internet who can access the
                    service such as a mobile phone, a computer or a digital
                    tablet.
                    <br />
                    -Usage Data it’s referred to the data that’s been collected
                    automatically, either generated by the use of the Service or
                    from the Service infrastructure itself. For example, how
                    many times the user accessed the website/app.
                  </p>
                  <p>
                    <strong>What Information Do We Collect?</strong>
                  </p>
                  <p className="legal-cont">
                    We collect information from you when you visit our
                    website/app, register on our site, place an order, subscribe
                    to our newsletter, respond to a survey or fill out a form.
                    -Email address
                    <br />
                    -Name / username
                    <br />
                    -Physical address
                    <br />
                    -Age
                    <br />
                    -Social media profile information
                  </p>
                  <p className="legal-cont">  
                  We also collect information from mobile devices for a better
                  user experience, although these features are completely
                  optional:
                  </p>
                  <p className="legal-cont">
                  -Location (GPS): Location data helps to create an accurate
                  representation of your interests, and this can be used to
                  bring more targeted and relevant ads to potential customers.
                  </p>
                  <p className="legal-cont">
                  -Phonebook (Contacts list): Your contacts list allows the
                  website/app to be much easier to use by the user, since
                  accessing your contacts from the app makes you save tons of
                  time.
                  </p>
                  <p className="legal-cont">
                  -Camera (Pictures): Granting camera permission allows the user
                  to upload any picture straight from the website/app, you can
                  safely deny camera permissions for this website/app.
                  </p>
                  <p><strong>How Do We Use The Information We Collect?</strong></p>
                  <p>
                  Any of the information we collect from you may be used in one
                  of the following ways:
                  </p>
                  <p className="legal-cont">
                  -To personalize your experience (your information helps us to
                  better respond to your individual needs)
                  <br />
                  -To improve our website/app (we continually strive to improve
                  our website/app offerings based on the information and
                  feedback we receive from you)
                  <br />
                  -To improve customer service (your information helps us to
                  more effectively respond to your customer service requests and
                  support needs)
                  <br />
                  -To process transactions
                  <br />
                  -To administer a contest, promotion, survey, or other site
                  feature
                  <br />
                  -To send periodic emails
                  </p>
                  <p>
                  <strong>
                    When does Yudimy use end user information from third
                    parties?
                  </strong>
                  </p>
                  <p>
                  Yudimy will collect End User Data necessary to provide the
                  Yudimy services to our customers.
                  </p>
                  <p className="legal-cont">
                  End users may voluntarily provide us with information they
                  have made available on social media websites. If you provide
                  us with any such information, we may collect publicly
                  available information from the social media websites you have
                  indicated. You can control how much of your information social
                  media websites make public by visiting these websites and
                  changing your privacy settings.
                  </p>
                  <p>
                  <strong>
                    When does Yudimy use customer information from third
                    parties?
                  </strong>
                  </p>
                  <p className="legal-cont">
                  We receive some information from the third parties when you
                  contact us. For example, when you submit your email address to
                  us to show interest in becoming a Yudimy customer, we receive
                  information from a third party that provides automated fraud
                  detection services to Yudimy. We also occasionally collect
                  information that is made publicly available on social media
                  websites. You can control how much of your information social
                  media websites make public by visiting these websites and
                  changing your privacy settings.
                  </p>
                  <p>
                  <strong>
                    Do we share the information we collect with third parties?
                  </strong>
                  </p>
                  <p className="legal-cont">
                  We may share the information that we collect, both personal
                  and non-personal, with third parties such as advertisers,
                  contest sponsors, promotional and marketing partners, and
                  others who provide our content or whose products or services
                  we think may interest you. We may also share it with our
                  current and future affiliated companies and business partners,
                  and if we are involved in a merger, asset sale or other
                  business reorganization, we may also share or transfer your
                  personal and non-personal information to our
                  successors-in-interest.
                  </p>
                  <p className="legal-cont">
                  We may engage trusted third party service providers to perform
                  functions and provide services to us, such as hosting and
                  maintaining our servers and the website/app, database storage
                  and management, e-mail management, storage marketing, credit
                  card processing, customer service and fulfilling orders for
                  products and services you may purchase through the
                  website/app. We will likely share your personal information,
                  and possibly some non-personal information, with these third
                  parties to enable them to perform these services for us and
                  for you.
                  </p>
                  <p className="legal-cont">
                  We may share portions of our log file data, including IP
                  addresses, for analytics purposes with third parties such as
                  web analytics partners, application developers, and ad
                  networks. If your IP address is shared, it may be used to
                  estimate general location and other technographics such as
                  connection speed, whether you have visited the website/app in
                  a shared location, and type of the device used to visit the
                  website/app. They may aggregate information about our
                  advertising and what you see on the website/app and then
                  provide auditing, research and reporting for us and our
                  advertisers.
                  </p>
                  <p className="legal-cont">
                  We may also disclose personal and non-personal information
                  about you to government or law enforcement officials or
                  private parties as we, in our sole discretion, believe
                  necessary or appropriate in order to respond to claims, legal
                  process (including subpoenas), to protect our rights and
                  interests or those of a third party, the safety of the public
                  or any person, to prevent or stop any illegal, unethical, or
                  legally actionable activity, or to otherwise comply with
                  applicable court orders, laws, rules and regulations.
                  </p>
                  <p>
                  <strong>
                    Where and when is information collected from customers and
                    end users?
                  </strong>
                  </p>
                  <p className="legal-cont">
                  Yudimy will collect personal information that you submit to
                  us. We may also receive personal information about you from
                  third parties as described above.
                  </p>
                 <p> <strong>How Do We Use Your Email Address?</strong> </p>
                 <p className="legal-cont">
                  By submitting your email address on this website/app, you
                  agree to receive emails from us. You can cancel your
                  participation in any of these email lists at any time by
                  clicking on the opt-out link or other unsubscribe option that
                  is included in the respective email. We only send emails to
                  people who have authorized us to contact them, either
                  directly, or through a third party. We do not send unsolicited
                  commercial emails, because we hate spam as much as you do. By
                  submitting your email address, you also agree to allow us to
                  use your email address for customer audience targeting on
                  sites like Facebook, where we display custom advertising to
                  specific people who have opted-in to receive communications
                  from us. Email addresses submitted only through the order
                  processing page will be used for the sole purpose of sending
                  you information and updates pertaining to your order. If,
                  however, you have provided the same email to us through
                  another method, we may use it for any of the purposes stated
                  in this Policy. Note: If at any time you would like to
                  unsubscribe from receiving future emails, we include detailed
                  unsubscribe instructions at the bottom of each email.
                </p>
                <p><strong>How Long Do We Keep Your Information?</strong></p>
                <p className="legal-cont">
                  We keep your information only so long as we need it to provide
                  Yudimy to you and fulfill the purposes described in this
                  policy. This is also the case for anyone that we share your
                  information with and who carries out services on our behalf.
                  When we no longer need to use your information and there is no
                  need for us to keep it to comply with our legal or regulatory
                  obligations, we’ll either remove it from our systems or
                  depersonalize it so that we can't identify you.
                </p>
                <p> <strong>How Do We Protect Your Information?</strong></p>
                 <p className="legal-cont">
                  We implement a variety of security measures to maintain the
                  safety of your personal information when you place an order or
                  enter, submit, or access your personal information. We offer
                  the use of a secure server. All supplied sensitive/credit
                  information is transmitted via Secure Socket Layer (SSL)
                  technology and then encrypted into our Payment gateway
                  providers database only to be accessible by those authorized
                  with special access rights to such systems, and are required
                  to keep the information confidential. After a transaction,
                  your private information (credit cards, social security
                  numbers, financials, etc.) is never kept on file. We cannot,
                  however, ensure or warrant the absolute security of any
                  information you transmit to Yudimy or guarantee that your
                  information on the Service may not be accessed, disclosed,
                  altered, or destroyed by a breach of any of our physical,
                  technical, or managerial safeguards.
                 </p>
                 <p>
                  <strong>
                    Could my information be transferred to other countries?
                  </strong>
                 </p>
                 <p className="legal-cont">
                  Yudimy is incorporated in Nigeria. Information collected via
                  our website, through direct interactions with you, or from use
                  of our help services may be transferred from time to time to
                  our offices or personnel, or to third parties, located
                  throughout the world, and may be viewed and hosted anywhere in
                  the world, including countries that may not have laws of
                  general applicability regulating the use and transfer of such
                  data. To the fullest extent allowed by applicable law, by
                  using any of the above, you voluntarily consent to the
                  trans-border transfer and hosting of such information.
                 </p>
                  <p>
                  <strong>
                    Is the information collected through the Yudimy Service
                    secure?
                  </strong>
                  </p>
                  <p className="legal-cont">
                  We take precautions to protect the security of your
                  information. We have physical, electronic, and managerial
                  procedures to help safeguard, prevent unauthorized access,
                  maintain data security, and correctly use your information.
                  However, neither people nor security systems are foolproof,
                  including encryption systems. In addition, people can commit
                  intentional crimes, make mistakes or fail to follow policies.
                  Therefore, while we use reasonable efforts to protect your
                  personal information, we cannot guarantee its absolute
                  security. If applicable law imposes any non-disclaimable duty
                  to protect your personal information, you agree that
                  intentional misconduct will be the standards used to measure
                  our compliance with that duty.
                  </p>
                 <p> <strong>Can I update or correct my information?</strong></p>
                  <p className="legal-cont">
                  The rights you have to request updates or corrections to the
                  information Yudimy collects depend on your relationship with
                  Yudimy. Personnel may update or correct their information as
                  detailed in our internal company employment policies.
                  </p>
                  <p className="legal-cont">
                  Customers have the right to request the restriction of certain
                  uses and disclosures of personally identifiable information as
                  follows. You can contact us in order to (1) update or correct
                  your personally identifiable information, (2) change your
                  preferences with respect to communications and other
                  information you receive from us, or (3) delete the personally
                  identifiable information maintained about you on our systems
                  (subject to the following paragraph), by cancelling your
                  account. Such updates, corrections, changes and deletions will
                  have no effect on other information that we maintain, or
                  information that we have provided to third parties in
                  accordance with this Privacy Policy prior to such update,
                  correction, change or deletion. To protect your privacy and
                  security, we may take reasonable steps (such as requesting a
                  unique password) to verify your identity before granting you
                  profile access or making corrections. You are responsible for
                  maintaining the secrecy of your unique password and account
                  information at all times.
                  </p>
                  <p className="legal-cont">
                  You should be aware that it is not technologically possible to
                  remove each and every record of the information you have
                  provided to us from our system. The need to back up our
                  systems to protect information from inadvertent loss means
                  that a copy of your information may exist in a non-erasable
                  form that will be difficult or impossible for us to locate.
                  Promptly after receiving your request, all personal
                  information stored in databases we actively use, and other
                  readily searchable media will be updated, corrected, changed
                  or deleted, as appropriate, as soon as and to the extent
                  reasonably and technically practicable.
                  </p>
                  <p className="legal-cont">
                  If you are an end user and wish to update, delete, or receive
                  any information we have about you, you may do so by contacting
                  the organization of which you are a customer.
                  </p>

                 <p> <strong>Personnel</strong></p>
                 <p className="legal-cont">
                  If you are a Yudimy worker or applicant, we collect
                  information you voluntarily provide to us. We use the
                  information collected for Human Resources purposes in order to
                  administer benefits to workers and screen applicants.
                 </p>
                 <p className="legal-cont">
                  You may contact us in order to (1) update or correct your
                  information, (2) change your preferences with respect to
                  communications and other information you receive from us, or
                  (3) receive a record of the information we have relating to
                  you. Such updates, corrections, changes and deletions will
                  have no effect on other information that we maintain, or
                  information that we have provided to third parties in
                  accordance with this Privacy Policy prior to such update,
                  correction, change or deletion.
                 </p>
                 <p><strong>Sale of Business</strong></p>
                  <p className="legal-cont">
                  We reserve the right to transfer information to a third party
                  in the event of a sale, merger or other transfer of all or
                  substantially all of the assets of Yudimy or any of its
                  Corporate Affiliates (as defined herein), or that portion of
                  Yudimy or any of its Corporate Affiliates to which the Service
                  relates, or in the event that we discontinue our business or
                  file a petition or have filed against us a petition in
                  bankruptcy, reorganization or similar proceeding, provided
                  that the third party agrees to adhere to the terms of this
                  Privacy Policy.
                  </p>
                <p>  <strong>Affiliates</strong> </p>
                 <p className="legal-cont">         
                  We may disclose information (including personal information)
                  about you to our Corporate Affiliates. For purposes of this
                  Privacy Policy, "Corporate Affiliate" means any person or
                  entity which directly or indirectly controls, is controlled by
                  or is under common control with Yudimy, whether by ownership
                  or otherwise. Any information relating to you that we provide
                  to our Corporate Affiliates will be treated by those Corporate
                  Affiliates in accordance with the terms of this Privacy
                  Policy.
                  </p>
                <p> <strong>Governing Law</strong></p>
                  <p className="legal-cont">
                  This Privacy Policy is governed by the laws of Nigeria without
                  regard to its conflict of laws provision. You consent to the
                  exclusive jurisdiction of the courts in connection with any
                  action or dispute arising between the parties under or in
                  connection with this Privacy Policy except for those
                  individuals who may have rights to make claims under Privacy
                  Shield, or the Swiss-US framework.
                  </p>
                  <p className="legal-cont">
                  The laws of Nigeria, excluding its conflicts of law rules,
                  shall govern this Agreement and your use of the website/app.
                  Your use of the website/app may also be subject to other
                  local, state, national, or international laws.
                  </p>
                  <p className="legal-cont">
                  By using Yudimy or contacting us directly, you signify your
                  Privacy Policy, you should not engage with our website, or use
                  our services. Continued use of the website, direct engagement
                  with us, or following the posting of changes to this Privacy
                  Policy that do not significantly affect the use or disclosure
                  of your personal information will mean that you accept those
                  changes.
                  </p>
                 <p><strong>Your Consent</strong></p>
                <p className="legal-cont">
                  We've updated our Privacy Policy to provide you with complete
                  transparency into what is being set when you visit our site
                  and how it's being used. By using our website/app, registering
                  an account, or making a purchase, you hereby consent to our
                  Privacy Policy and agree to its terms.
                </p>
                <p><strong>Links to Other Websites</strong></p>
                 <p className="legal-cont">
                  Our service may contain links to other websites that are not
                  operated by Us. If You click on a third party link, You will
                  be directed to that third party's site. We strongly advise You
                  to review the Privacy Policy of every site You visit. We have
                  no control over and assume no responsibility for the content,
                  privacy policies or practices of any third party sites or
                  services.
                  </p>
                <p><strong>Cookies</strong></p>
                <p className="legal-cont">
                  Yudimy uses "Cookies" to identify the areas of our website
                  that you have visited. A Cookie is a small piece of data
                  stored on your computer or mobile device by your web browser.
                  We use Cookies to enhance the performance and functionality of
                  our website/app but are non-essential to their use. However,
                  without these cookies, certain functionality like videos may
                  become unavailable or you would be required to enter your
                  login details every time you visit the website/app as we would
                  not be able to remember that you had logged in previously.
                  Most web browsers can be set to disable the use of Cookies.
                  However, if you disable Cookies, you may not be able to access
                  functionality on our website correctly or at all. We never
                  place Personally Identifiable Information in Cookies.
                  </p>
                  <p>
                  <strong>
                    Blocking and disabling cookies and similar technologies
                  </strong>
                  </p>
                  <p className="legal-cont">
                  Wherever you're located you may also set your browser to block
                  cookies and similar technologies, but this action may block
                  our essential cookies and prevent our website from functioning
                  properly, and you may not be able to fully utilize all of its
                  features and services. You should also be aware that you may
                  also lose some saved information (e.g. saved login details,
                  site preferences) if you block cookies on your browser.
                  Different browsers make different controls available to you.
                  Disabling a cookie or category of cookie does not delete the
                  cookie from your browser, you will need to do this yourself
                  from within your browser, you should visit your browser's help
                  menu for more information.
                  </p>
                 <p> <strong>Remarketing Services</strong></p>
                  <p className="legal-cont">  
                  We use remarketing services. What Is Remarketing? In digital
                  marketing, remarketing (or retargeting) is the practice of
                  serving ads across the internet to people who have already
                  visited your website. It allows your company to seem like
                  they're “following” people around the internet by serving ads
                  on the websites and platforms they use most.
                  </p>
                 <p> <strong>Payment Details</strong></p>
                <p className="legal-cont">
                  In respect to any credit card or other payment processing
                  details you have provided us, we commit that this confidential
                  information will be stored in the most secure manner possible.
                </p>
                <p><strong>Kids' Privacy</strong></p>
                  <p className="legal-cont"> 
                  We collect information from kids under the age of 13 just to
                  better our services. If You are a parent or guardian and You
                  are aware that Your child has provided Us with Personal Data
                  without your permission, please contact Us. If We become aware
                  that We have collected Personal Data from anyone under the age
                  of 13 without verification of parental consent, We take steps
                  to remove that information from Our servers.
                  </p>
                <p>  <strong>Changes To Our Privacy Policy</strong></p>
                  <p className="legal-cont">
                  We may change our Service and policies, and we may need to
                  make changes to this Privacy Policy so that they accurately
                  reflect our Service and policies. Unless otherwise required by
                  law, we will notify you (for example, through our Service)
                  before we make changes to this Privacy Policy and give you an
                  opportunity to review them before they go into effect. Then,
                  if you continue to use the Service, you will be bound by the
                  updated Privacy Policy. If you do not want to agree to this or
                  any updated Privacy Policy, you can delete your account.
                  </p>
                  <p><strong>Third-Party Services</strong></p>
                  <p className="legal-cont">
                  We may display, include or make available third-party content
                  (including data, information, applications and other products
                  services) or provide links to third-party websites or services
                  ("Third- Party Services"). You acknowledge and agree that
                  Yudimy shall not be responsible for any Third-Party Services,
                  including their accuracy, completeness, timeliness, validity,
                  copyright compliance, legality, decency, quality or any other
                  aspect thereof. Yudimy does not assume and shall not have any
                  liability or responsibility to you or any other person or
                  entity for any Third-Party Services. Third-Party Services and
                  links thereto are provided solely as a convenience to you and
                  you access and use them entirely at your own risk and subject
                  to such third parties' terms and conditions.
                  </p>
                  <p><strong> -Invisible reCAPTCHA</strong></p>
                  <p className="legal-cont">
                  Invisible reCAPTCHA analyzes activity on a job post (e.g.
                  mouse movements and typing patterns) to determine if a user is
                  a robot. Invisible reCAPTCHA service may collect information
                  from Your device. The information gathered by Invisible
                  reCAPTCHA is held in accordance with its Privacy Policy
                  </p>
                 <p> <strong>-Google Places</strong></p>
                 <p className="legal-cont">
                  Google Places is a service that returns information about
                  places using HTTP requests. It is operated by Google. Google
                  Places service may collect information from You and from Your
                  Device for security purposes. The information gathered by
                  Google Places is held in accordance with the Privacy Policy of
                  Google
                  </p>
                  <p className="legal-cont">
                  Information Regarding Your Data Protection Rights Under
                  General Data Protection Regulation (GDPR)
                  </p>
                  <p className="legal-cont">
                  For the purpose of this Privacy Policy, we are a Data
                  Controller of your personal information.
                  </p>
                  <p className="legal-cont">
                  If you are from the European Economic Area (EEA), our legal
                  basis for collecting and using your personal information, as
                  described in this Privacy Policy, depends on the information
                  we collect and the specific context in which we collect it. We
                  may process your personal information because:
                  </p>
                  <p className="legal-cont">
                  -We need to perform a contract with you, such as when you use
                  our services<br/>
                  -You have given us permission to do so<br/>
                  -The processing is in our legitimate interests and it's not
                  overridden by your rights<br/>
                  -For payment processing purposes<br/>
                  -To comply with the law<br/>
                  </p>
                  <p className="legal-cont">
                  If you are a resident of the European Economic Area (EEA), you
                  have certain data protection rights. In certain circumstances,
                  you have the following data protection rights:
                  </p>
                  <p className="legal-cont">
                  -The right to access, update or to delete the personal
                  information we have on you<br/>
                  -The right of rectification<br/>
                  -The right to object<br/>
                  -The right of restriction<br/>
                  -The right to data portability<br/>
                  -The right to withdraw consent<br/>
                  </p>
                  <p className="legal-cont">
                  Please note that we may ask you to verify your identity before
                  responding to such requests.
                  </p>
                  <p className="legal-cont">
                  You have the right to complain to a Data Protection Authority
                  about our collection and use of your personal information. For
                  more information, please contact your local data protection
                  authority in the European Economic Area (EEA).
                  </p>
                 <p> <strong>California Residents</strong></p>
                  <p className="legal-cont">
                  The California Consumer Privacy Act (CCPA) requires us to
                  disclose categories of Personal Information we collect and how
                  we use it, the categories of sources from whom we collect
                  Personal Information, and the third parties with whom we share
                  it, which we have explained above.
                  </p>
                  <p className="legal-cont">
                  We are also required to communicate information about rights
                  California residents have under California law. You may
                  exercise the following rights:
                  </p>
                  <p className="legal-cont">
                  -Right to Know and Access. You may submit a verifiable request
                  for information regarding the: (1) categories of Personal
                  Information we collect, use, or share; (2) purposes for which
                  categories of Personal Information are collected or used by
                  us; (3) categories of sources from which we collect Personal
                  Information; and (4) specific pieces of Personal Information
                  we have collected about you.<br/>
                  -Right to Equal Service. We will not discriminate against you
                  if you exercise your privacy rights.<br/>
                  -Right to Delete. You may submit a verifiable request to close
                  your account and we will delete Personal Information about you
                  that we have collected.<br/>
                  -Request that a business that sells a consumer's personal
                  data, not sell the consumer's personal data.
                  </p>
                  <p className="legal-cont">
                  If you make a request, we have one month to respond to you. If
                  you would like to exercise any of these rights, please contact
                  us.<br/>
                  We do not sell the Personal Information of our users.<br/>
                  For more information about these rights, please contact us.
                  </p>
                  <p>
                  <strong>
                    California Online Privacy Protection Act (CalOPPA)
                  </strong>
                  </p>
                  <p className="legal-cont">
                  According to CalOPPA, personal information is defined as any
                  data that may be used to identify a person Under the CalOPPA,
                  California consumers have the right to:
                  </p>
                  <p className="legal-cont">
                  -Request that a business that collects a consumer's personal
                  data disclose the categories and specific pieces of personal
                  data that a business has collected about consumers.<br/>
                  -Request that a business delete any personal data about the
                  consumer that a business has collected.<br/>
                  -Request that a business that sells a consumer's personal
                  data, not sell the consumer's personal data.<br/>
                  <br/>
                  If you make a request, we have one month to respond to you. If
                  you would like to exercise any of these rights, please contact
                  us.
                  </p>
                 <p><strong>Contact Us</strong></p>
                  
                <p> Don't hesitate to contact us if you have any questions.</p>
                  
                  -Via Email: ask@yudimy.com<br/>
                  -Via Phone Number: +2348031301167<br/>
                  -Via this Link: https://clarity.yudimy.com/contactus<br/>
                </Card.Body>
              </Card>
            </Col>
          </div>
        </Container>
      </div>
      <Footer />
    </div>
  );
};
export default Privacy;
