import React from "react";
import { Container, Col, Card } from "react-bootstrap";
import "./privacy_policy.css";
import Footer from "../HomeComponents/newfooter";

const Terms = () => {
  return (
    <div>
      <div className="policy_page">
        <Container>
          <div className="privacy-title">
            <h2>Terms & Conditions</h2>
          </div>
        </Container>
      </div>
      <div className="policy-section">
        <Container>
          <div className="centralized-content">
            <Col md={11} className="policy-content">
              <Card className="policy-card">
                <Card.Header className="policy-header">
                  Update at 2020-09-09
                </Card.Header>
                <Card.Body className="policy_card-body">
                  <p>
                    <strong> License</strong>{" "}
                  </p>
                  <p>
                    Yudimy grants you a revocable, non-exclusive,
                    non-transferable, limited license to download, install and
                    use the website/app strictly in accordance with the terms of
                    this Agreement.
                  </p>
                  <p>
                    These Terms & Conditions are a contract between you and
                    Yudimy (referred to in these Terms & Conditions as "Yudimy",
                    "us", "we" or "our"), the provider of the Yudimy website and
                    the services accessible from the Yudimy website (which are
                    collectively referred to in these Terms & Conditions as the
                    "Yudimy Service").
                  </p>
                  <p className="legal-cont">
                    You are agreeing to be bound by these Terms & Conditions. If
                    you do not agree to these Terms & Conditions, please do not
                    use the Yudimy Service. In these Terms & Conditions, "you"
                    refers both to you as an individual and to the entity you
                    represent. If you violate any of these Terms & Conditions,
                    we reserve the right to cancel your account or block access
                    to your account without notice.
                  </p>
                  <p>
                    {" "}
                    <strong> Meanings</strong>
                  </p>
                  <p>
                    <strong> For this Terms & Conditions:</strong>
                  </p>
                  <p className="legal-cont">
                    -You are referred to the person who accessed the Service, or
                    the company, or other legal entity on behalf of which such
                    individual is accessing or using the Service, as applicable.
                    -Company (referred to as either "the Company", "We", "Us" or
                    "Our" in this Agreement) refers to Yudimy Services Ltd, 3
                    Samuel Street, Ogudu, Lagos -Service is referred to the
                    website/app. -Service Provider means any natural or legal
                    person who processes the data on behalf of Yudimy. It refers
                    to third-party companies or individuals employed by Yudimy
                    to facilitate the Service, to provide the Service on behalf
                    of Yudimy, to perform services related to the Service or to
                    assist Yudimy in analysing how the Service is used.
                    -Third-party Social Media Service could be any website or
                    social network website in which a User can log in or create
                    an account to use the Service. -Personal Data is any
                    information that relates to an identified or identifiable
                    individual. -Cookies are a small amount of data generated by
                    a website and saved by your web browser. Its purpose is to
                    remember information about you, similar to a preference file
                    created by a software application.
                  </p>
                  <p>
                    {" "}
                    <strong> Maximizing Human Potential</strong>{" "}
                  </p>
                  <p className="legal-cont">
                    -Device could be any device with internet who can access the
                    service such as a mobile phone, a computer or a digital
                    tablet. -Usage Data it’s referred to the data that’s been
                    collected automatically, either generated by the use of the
                    Service or from the Service infrastructure itself. For
                    example, how many times the user accessed the website/app.
                  </p>
                  <p>
                    {" "}
                    <strong> Restrictions</strong>
                  </p>
                  <p> You agree not to, and you will not permit others to: </p>
                  <p className="legal-cont">
                    -License, sell, rent, lease, assign, distribute, transmit,
                    host, outsource, disclose or otherwise commercially exploit
                    the website/app or make the platform available to any third
                    party. -Modify, make derivative works of, disassemble,
                    decrypt, reverse compile or reverse engineer any part of the
                    website/app. -Remove, alter or obscure any proprietary
                    notice (including any notice of copyright or trademark) of
                    Yudimy or its affiliates, partners, suppliers or the
                    licensors of the website/app.
                  </p>
                  <p>
                    <strong> Return and Refund Policy</strong>
                  </p>
                  <p className="legal-cont">
                    Thanks for shopping at Yudimy. We appreciate the fact that
                    you like to buy the stuff we build. We also want to make
                    sure you have a rewarding experience while you’re exploring,
                    evaluating, and purchasing our products. As with any
                    shopping experience, there are terms and conditions that
                    apply to transactions at Yudimy. We’ll be as brief as our
                    attorneys will allow. The main thing to remember is that by
                    placing an order or making a purchase at Yudimy, you agree
                    to the terms along with Policy. If, for any reason, You are
                    not completely satisfied with any good or service that we
                    provide, don't hesitate to contact us and we will discuss
                    any of the issues you are going through with our product.
                  </p>
                  <p>
                    {" "}
                    <strong> Your Suggestions </strong>
                  </p>
                  <p className="legal-cont">
                    Any feedback, comments, ideas, improvements or suggestions
                    (collectively, "Suggestions") provided by you to Yudimy with
                    respect to the website/app shall remain the sole and
                    exclusive property of Yudimy. Yudimy shall be free to use,
                    copy, modify, publish, or redistribute the Suggestions for
                    any purpose and in any way without any credit or any
                    compensation to you.
                  </p>
                  <p>
                    <strong>Your Consent </strong>
                  </p>
                  <p className="legal-cont">
                    We've updated our Terms & Conditions to provide you with
                    complete transparency into what is being set when you visit
                    our site and how it's being used. By using our website/app,
                    registering an account, or making a purchase, you hereby
                    consent to our Terms & Conditions.
                  </p>
                  <p>
                    {" "}
                    <strong> Links to Other Websites </strong>
                  </p>
                  <p className="legal-cont">
                    Our service may contain links to other websites that are not
                    operated by Us. If You click on a third party link, You will
                    be directed to that third party's site. We strongly advise
                    You to review the Terms & Conditions of every site You
                    visit. We have no control over and assume no responsibility
                    for the content, Terms & Conditions or practices of any
                    third party sites or services.
                  </p>
                  <p>
                    <strong> Cookies </strong>
                  </p>
                  <p className="legal-cont">
                    Yudimy uses "Cookies" to identify the areas of our website
                    that you have visited. A Cookie is a small piece of data
                    stored on your computer or mobile device by your web
                    browser. We use Cookies to enhance the performance and
                    functionality of our website/app but are non-essential to
                    their use. However, without these cookies, certain
                    functionality like videos may become unavailable or you
                    would be required to enter your login details every time you
                    visit the website/app as we would not be able to remember
                    that you had logged in previously. Most web browsers can be
                    set to disable the use of Cookies. However, if you disable
                    Cookies, you may not be able to access functionality on our
                    website correctly or at all. We never place Personally
                    Identifiable Information in Cookies.
                  </p>
                  <p>
                    <strong>Changes To Our Terms & Conditions</strong>
                  </p>
                  <p className="legal-cont">
                    You acknowledge and agree that yudimy may stop (permanently
                    or temporarily) providing the Service (or any features
                    within the Service) to you or to users generally at Yudimy’s
                    sole discretion, without prior notice to you. You may stop
                    using the Service at any time. You do not need to
                    specifically inform Yudimy when you stop using the Service.
                    You acknowledge and agree that if yudimy disables access to
                    your account, you may be prevented from accessing the
                    Service, your account details or any files or other
                    materials which is contained in your account. If we decide
                    to change our Terms & Conditions, we will post those changes
                    on this page, and/or update the Terms & Conditions
                    modification date below.
                  </p>
                  <p>
                    <strong>Modifications to Our website/app </strong>
                  </p>
                  <p className="legal-cont">
                    Yudimy reserves the right to modify, suspend or discontinue,
                    temporarily or permanently, the website/app or any service
                    to which it connects, with or without notice and without
                    liability to you.
                  </p>
                  <p>
                    <strong> Updates to Our website/app</strong>
                  </p>
                  <p>
                    Yudimy may from time to time provide enhancements or
                    improvements to the features/ functionality of the
                    website/app, which may include patches, bug fixes, updates,
                    upgrades and other modifications ("Updates").
                  </p>
                  <p>
                    Updates may modify or delete certain features and/or
                    functionalities of the website/app. You agree that Yudimy
                    has no obligation to (i) provide any Updates, or (ii)
                    continue to provide or enable any particular features and/or
                    functionalities of the website/app to you.
                  </p>
                  <p className="legal-cont">
                    You further agree that all Updates will be (i) deemed to
                    constitute an integral part of the website/app, and (ii)
                    subject to the terms and conditions of this Agreement.
                  </p>
                  <p>
                    <strong> Third-Party Services </strong>
                  </p>
                  <p>
                    We may display, include or make available third-party
                    content (including data, information, applications and other
                    products services) or provide links to third-party websites
                    or services ("Third- Party Services").
                  </p>
                  <p className="legal-cont">
                    You acknowledge and agree that Yudimy shall not be
                    responsible for any Third-Party Services, including their
                    accuracy, completeness, timeliness, validity, copyright
                    compliance, legality, decency, quality or any other aspect
                    thereof. Yudimy does not assume and shall not have any
                    liability or responsibility to you or any other person or
                    entity for any Third-Party Services. Third-Party Services
                    and links thereto are provided solely as a convenience to
                    you and you access and use them entirely at your own risk
                    and subject to such third parties' terms and conditions.
                  </p>
                  <p>
                    {" "}
                    <strong>Term and Termination</strong>
                  </p>
                  <p>
                    This Agreement shall remain in effect until terminated by
                    you or Yudimy.
                  </p>
                  <p>
                    Yudimy may, in its sole discretion, at any time and for any
                    or no reason, suspend or terminate this Agreement with or
                    without prior notice.
                  </p>
                  <p>
                    This Agreement will terminate immediately, without prior
                    notice from Yudimy, in the event that you fail to comply
                    with any provision of this Agreement. You may also terminate
                    this Agreement by deleting the website/app and all copies
                    thereof from your computer.
                  </p>
                  <p className="legal-cont">
                    Upon termination of this Agreement, you shall cease all use
                    of the website/app and delete all copies of the website/app
                    from your computer. Termination of this Agreement will not
                    limit any of Yudimy's rights or remedies at law or in equity
                    in case of breach by you (during the term of this Agreement)
                    of any of your obligations under the present Agreement.
                  </p>
                  <p>
                    <strong> Copyright Infringement Notice</strong>
                  </p>
                  <p className="legal-cont">
                    If you are a copyright owner or such owner’s agent and
                    believe any material on our website/app constitutes an
                    infringement on your copyright, please contact us setting
                    forth the following information: (a) a physical or
                    electronic signature of the copyright owner or a person
                    authorized to act on his behalf; (b) identification of the
                    material that is claimed to be infringing; (c) your contact
                    information, including your address, telephone number, and
                    an email; (d) a statement by you that you have a good faith
                    belief that use of the material is not authorized by the
                    copyright owners; and (e) the a statement that the
                    information in the notification is accurate, and, under
                    penalty of perjury you are authorized to act on behalf of
                    the owner.
                  </p>
                  <p>
                    <strong>Indemnification</strong>
                  </p>
                  <p className="legal-cont">
                    You agree to indemnify and hold Yudimy and its parents,
                    subsidiaries, affiliates, officers, employees, agents,
                    partners and licensors (if any) harmless from any claim or
                    demand, including reasonable attorneys' fees, due to or
                    arising out of your: (a) use of the website/app; (b)
                    violation of this Agreement or any law or regulation; or (c)
                    violation of any right of a third party.
                  </p>
                  <p>
                    <strong> No Warranties</strong>
                  </p>
                  <p>
                    The website/app is provided to you "AS IS" and "AS
                    AVAILABLE" and with all faults and defects without warranty
                    of any kind. To the maximum extent permitted under
                    applicable law, Yudimy, on its own behalf and on behalf of
                    its affiliates and its and their respective licensors and
                    service providers, expressly disclaims all warranties,
                    whether express, implied, statutory or otherwise, with
                    respect to the website/app, including all implied warranties
                    of merchantability, fitness for a particular purpose, title
                    and non-infringement, and warranties that may arise out of
                    course of dealing, course of performance, usage or trade
                    practice. Without limitation to the foregoing, Yudimy
                    provides no warranty or undertaking, and makes no
                    representation of any kind that the website/app will meet
                    your requirements, achieve any intended results, be
                    compatible or work with any other software, , systems or
                    services, operate without interruption, meet any performance
                    or reliability standards or be error free or that any errors
                    or defects can or will be corrected.
                  </p>
                  <p>
                    Without limiting the foregoing, neither Yudimy nor any
                    Yudimy's provider makes any representation or warranty of
                    any kind, express or implied: (i) as to the operation or
                    availability of the website/app, or the information,
                    content, and materials or products included thereon; (ii)
                    that the website/app will be uninterrupted or error-free;
                    (iii) as to the accuracy, reliability, or currency of any
                    information or content provided through the website/app; or
                    (iv) that the website/app, its servers, the content, or
                    emails sent from or on behalf of Yudimy are free of viruses,
                    scripts, trojan horses, worms, malware, timebombs or other
                    harmful components.
                  </p>
                  <p className="legal-cont">
                    Some jurisdictions do not allow the exclusion of or
                    limitations on implied warranties or the limitations on the
                    applicable statutory rights of a consumer, so some or all of
                    the above exclusions and limitations may not apply to you.
                  </p>
                  <p>
                    {" "}
                    <strong> Limitation of Liability </strong>
                  </p>
                  <p className="legal-cont">
                    Notwithstanding any damages that you might incur, the entire
                    liability of Yudimy and any of its suppliers under any
                    provision of this Agreement and your exclusive remedy for
                    all of the foregoing shall be limited to the amount actually
                    paid by you for the website/app. To the maximum extent
                    permitted by applicable law, in no event shall Yudimy or its
                    suppliers be liable for any special, incidental, indirect,
                    or consequential damages whatsoever (including, but not
                    limited to, damages for loss of profits, for loss of data or
                    other information, for business interruption, for personal
                    injury, for loss of privacy arising out of or in any way
                    related to the use of or inability to use the website/app,
                    thirdparty software and/or third-party hardware used with
                    the website/app, or otherwise in connection with any
                    provision of this Agreement), even if Yudimy or any supplier
                    has been advised of the possibility of such damages and even
                    if the remedy fails of its essential purpose. Some
                    states/jurisdictions do not allow the exclusion or
                    limitation of incidental or consequential damages, so the
                    above limitation or exclusion may not apply to you.
                  </p>
                  <p>
                    <strong> Severability</strong>
                  </p>
                  <p>
                    If any provision of this Agreement is held to be
                    unenforceable or invalid, such provision will be changed and
                    interpreted to accomplish the objectives
                  </p>
                  <p>
                    of such provision to the greatest extent possible under
                    applicable law and the remaining provisions will continue in
                    full force and effect.
                  </p>
                  <p className="legal-cont">
                    This Agreement, together with the Privacy Policy and any
                    other legal notices published by Yudimy on the Services,
                    shall constitute the entire agreement between you and Yudimy
                    concerning the Services. If any provision of this Agreement
                    is deemed invalid by a court of competent jurisdiction, the
                    invalidity of such provision shall not affect the validity
                    of the remaining provisions of this Agreement, which shall
                    remain in full force and effect. No waiver of any term of
                    this Agreement shall be deemed a further or continuing
                    waiver of such term or any other term, and failure to assert
                    any right or provision under this Agreement shall not
                    constitute a waiver of such right or provision. YOU AND
                    Yudimy AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR
                    RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR
                    AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF
                    ACTION IS PERMANENTLY BARRED.
                  </p>
                  <p>
                    <strong> Waiver</strong>{" "}
                  </p>
                  <p className="legal-cont">
                    Except as provided herein, the failure to exercise a right
                    or to require performance of an obligation under this
                    Agreement shall not effect a party's ability to exercise
                    such right or require such performance at any time
                    thereafter nor shall be the waiver of a breach constitute
                    waiver of any subsequent breach. No failure to exercise, and
                    no delay in exercising, on the part of either party, any
                    right or any power under this Agreement shall operate as a
                    waiver of that right or power. Nor shall any single or
                    partial exercise of any right or power under this Agreement
                    preclude further exercise of that or any other right granted
                    herein. In the event of a conflict between this Agreement
                    and any applicable purchase or other terms, the terms of
                    this Agreement shall govern.
                  </p>
                  <p>
                    <strong> Amendments to this Agreement</strong>
                  </p>
                  <p className="legal-cont">
                    Yudimy reserves the right, at its sole discretion, to modify
                    or replace this Agreement at any time. If a revision is
                    material we will provide at least 30 days' notice prior to
                    any new terms taking effect. What constitutes a material
                    change will be determined at our sole discretion. By
                    continuing to access or use our website/app after any
                    revisions become effective, you agree to be bound by the
                    revised terms. If you do not agree to the new terms, you are
                    no longer authorized to use Yudimy.
                  </p>
                  <p>
                    {" "}
                    <strong> Entire Agreement </strong>
                  </p>
                  <p className="legal-cont">
                    The Agreement constitutes the entire agreement between you
                    and Yudimy regarding your use of the website/app and
                    supersedes all prior and contemporaneous written or oral
                    agreements between you and Yudimy. You may be subject to
                    additional terms and conditions that apply when you use or
                    purchase other Yudimy's services, which Yudimy will provide
                    to you at the time of such use or purchase.
                  </p>
                  <p>
                    {" "}
                    <strong>Updates to Our Terms </strong>
                  </p>
                  <p className="legal-cont">
                    We may change our Service and policies, and we may need to
                    make changes to these Terms so that they accurately reflect
                    our Service and policies. Unless otherwise required by law,
                    we will notify you (for example, through our Service) before
                    we make changes to these Terms and give you an opportunity
                    to review them before they go into effect. Then, if you
                    continue to use the Service, you will be bound by the
                    updated Terms. If you do not want to agree to these or any
                    updated Terms, you can delete your account.
                  </p>
                  <p>
                    <strong> Intellectual Property</strong>
                  </p>
                  <p className="legal-cont">
                    The website/app and its entire contents, features and
                    functionality (including but not limited to all information,
                    software, text, displays, images, video and audio, and the
                    design, selection and arrangement thereof), are owned by
                    Yudimy, its licensors or other providers of such material
                    and are protected by Nigeria and international copyright,
                    trademark, patent, trade secret and other intellectual
                    property or proprietary rights laws. The material may not be
                    copied, modified, reproduced, downloaded or distributed in
                    any way, in whole or in part, without the express prior
                    written permission of Yudimy, unless and except as is
                    expressly provided in these Terms & Conditions. Any
                    unauthorized use of the material is prohibited.
                  </p>
                  <p>
                    {" "}
                    <strong> Agreement to Arbitrate </strong>
                  </p>
                  <p className="legal-cont">
                    This section applies to any dispute EXCEPT IT DOESN’T
                    INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR
                    EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF
                    YOUR OR INTELLECTUAL PROPERTY RIGHTS. The term “dispute”
                    means any dispute, action, or other controversy between you
                    and Yudimy concerning the Services or this agreement,
                    whether in contract, warranty, tort, statute, regulation,
                    ordinance, or any other legal or equitable basis. “Dispute”
                    will be given the broadest possible meaning allowable under
                    law.
                  </p>
                  <p>
                    <strong> Notice of Dispute </strong>
                  </p>
                  <p className="legal-cont">
                    In the event of a dispute, you or Yudimy must give the other
                    a Notice of Dispute, which is a written statement that sets
                    forth the name, address, and contact information of the
                    party giving it, the facts giving rise to the dispute, and
                    the relief requested. You must send any Notice of Dispute
                    via email to: ask@yudimy.com. Yudimy will send any Notice of
                    Dispute to you by mail to your address if we have it, or
                    otherwise to your email address. You and Yudimy will attempt
                    to resolve any dispute through informal negotiation within
                    sixty (60) days from the date the Notice of Dispute is sent.
                    After sixty (60) days, you or Yudimy may commence
                    arbitration.
                  </p>
                  <p>
                    <strong> Binding Arbitration</strong>
                  </p>
                  <p className="legal-cont">
                    If you and Yudimy don’t resolve any dispute by informal
                    negotiation, any other effort to resolve the dispute will be
                    conducted exclusively by binding arbitration as described in
                    this section. You are giving up the right to litigate (or
                    participate in as a party or class member) all disputes in
                    court before a judge or jury. The dispute shall be settled
                    by binding arbitration in accordance with the commercial
                    arbitration rules of the American Arbitration Association.
                    Either party may seek any interim or preliminary injunctive
                    relief from any court of competent jurisdiction, as
                    necessary to protect the party’s rights or property pending
                    the completion of arbitration. Any and all legal,
                    accounting, and other costs, fees, and expenses incurred by
                    the prevailing party shall be borne by the nonprevailing
                    party.
                  </p>
                  <p>
                    {" "}
                    <strong>Submissions and Privacy </strong>
                  </p>
                  <p className="legal-cont">
                    In the event that you submit or post any ideas, creative
                    suggestions, designs, photographs, information,
                    advertisements, data or proposals, including ideas for new
                    or improved products, services, features, technologies or
                    promotions, you expressly agree that such submissions will
                    automatically be treated as non-confidential and
                    non-proprietary and will become the sole property of Yudimy
                    without any compensation or credit to you whatsoever. Yudimy
                    and its affiliates shall have no obligations with respect to
                    such submissions or posts and may use the ideas contained in
                    such submissions or posts for any purposes in any medium in
                    perpetuity, including, but not limited to, developing,
                    manufacturing, and marketing products and services using
                    such ideas.
                  </p>
                  <p>
                    <strong> Promotions </strong>
                  </p>
                  <p>
                    Yudimy may, from time to time, include contests, promotions,
                    sweepstakes, or other activities (“Promotions”) that require
                    you to submit material or information concerning yourself.
                    Please note that all Promotions may be governed by separate
                    rules that may contain certain eligibility requirements,
                    such as restrictions as to age and geographic location. You
                  </p>
                  <p className="legal-cont">
                    are responsible to read all Promotions rules to determine
                    whether or not you are eligible to participate. If you enter
                    any Promotion, you agree to abide by and to comply with all
                    Promotions Rules. Additional terms and conditions may apply
                    to purchases of goods or services on or through the
                    Services, which terms and conditions are made a part of this
                    Agreement by this reference.
                  </p>
                  <p>
                    {" "}
                    <strong> Typographical Errors </strong>
                  </p>
                  <p className="legal-cont">
                    In the event a product and/or service is listed at an
                    incorrect price or with incorrect information due to
                    typographical error, we shall have the right to refuse or
                    cancel any orders placed for the product and/or service
                    listed at the incorrect price. We shall have the right to
                    refuse or cancel any such order whether or not the order has
                    been confirmed and your credit card charged. If your credit
                    card has already been charged for the purchase and your
                    order is canceled, we shall immediately issue a credit to
                    your credit card account or other payment account in the
                    amount of the charge.
                  </p>
                  <p>
                    <strong>Miscellaneous</strong>
                  </p>
                  <p className="legal-cont">
                    If for any reason a court of competent jurisdiction finds
                    any provision or portion of these Terms & Conditions to be
                    unenforceable, the remainder of these Terms & Conditions
                    will continue in full force and effect. Any waiver of any
                    provision of these Terms & Conditions will be effective only
                    if in writing and signed by an authorized representative of
                    Yudimy. Yudimy will be entitled to injunctive or other
                    equitable relief (without the obligations of posting any
                    bond or surety) in the event of any breach or anticipatory
                    breach by you. Yudimy operates and controls the Yudimy
                    Service from its offices in Nigeria. The Service is not
                    intended for distribution to or use by any person or entity
                    in any jurisdiction or country where such distribution or
                    use would be contrary to law or regulation. Accordingly,
                    those persons who choose to access the Yudimy Service from
                    other locations do so on their own initiative and are solely
                    responsible for compliance with local laws, if and to the
                    extent local laws are applicable. These Terms & Conditions
                    (which include and incorporate the Yudimy Privacy Policy)
                    contains the entire understanding, and supersedes all prior
                    understandings, between you and Yudimy concerning its
                    subject matter, and cannot be changed or modified by you.
                    The section headings used in this Agreement are for
                    convenience only and will not be given any legal import.
                  </p>
                  <p>
                    {" "}
                    <strong>Disclaimer </strong>
                  </p>
                  <p>
                    Yudimy is not responsible for any content, code or any other
                    imprecision.
                  </p>
                  <p>Yudimy does not provide warranties or guarantees.</p>
                  <p>
                    In no event shall Yudimy be liable for any special, direct,
                    indirect, consequential, or incidental damages or any
                    damages whatsoever, whether in an action of contract,
                    negligence or other tort, arising out of or in connection
                    with the use of the Service or the contents of the Service.
                    Yudimy reserves the right to make additions, deletions, or
                    modifications to the contents on the Service at any time
                    without prior notice.
                  </p>
                  <p className="legal-cont">
                    The Yudimy Service and its contents are provided "as is" and
                    "as available" without any warranty or representations of
                    any kind, whether express or implied. Yudimy is a
                    distributor and not a publisher of the content supplied by
                    third parties; as such, Yudimy exercises no editorial
                    control over such content and makes no warranty or
                    representation as to the accuracy, reliability or currency
                    of any information, content, service or merchandise provided
                    through or accessible via the Yudimy Service. Without
                    limiting the foregoing, Yudimy specifically disclaims all
                    warranties and representations in any content transmitted on
                    or in connection with the Yudimy Service or on sites that
                    may appear as links on the Yudimy Service, or in the
                    products provided as a part of, or otherwise in connection
                    with, the Yudimy Service, including without limitation any
                    warranties of merchantability, fitness for a particular
                    purpose or non-infringement of third party rights. No oral
                    advice or written information given by Yudimy or any of its
                    affiliates, employees, officers, directors, agents, or the
                    like will create a warranty. Price and availability
                    information is subject to change without notice. Without
                    limiting the foregoing, Yudimy does not warrant that the
                    Yudimy Service will be uninterrupted, uncorrupted, timely,
                    or error-free.
                  </p>
                  <p>
                    <strong>Contact Us</strong>
                  </p>
                  <p>
                    {" "}
                    Don't hesitate to contact us if you have any questions.{" "}
                  </p>
                  -Via Email: ask@yudimy.com<br />
                  -Via Phone Number: +2348031301167<br />
                  -Via this Link: https://clarity.yudimy.com/contactus
                </Card.Body>
              </Card>
            </Col>
          </div>
        </Container>
      </div>
      <Footer />
    </div>
  );
};
export default Terms;
